version: '2'
services:
    daspanel-php-fpm-7.0:
        image: daspanel/php-fpm-7.0
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - backend
        env_file:
            - daspanel.env
networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge


